=== ICV-23-24/xml-schemas-JoanApr/EJERCICIOS_XML/Tarea2/Tarea2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="afiliado">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="DNI_NIE" type="xsd:string"></xsd:element>
                <xsd:element name="nombre" type="xsd:string"></xsd:element>
                <xsd:element name="apellidos" type="xsd:string"></xsd:element>
                <xsd:element name="fechaNacimiento" type="tipofecha"></xsd:element>
                <xsd:element name="situacionLaboral" type="tiposituacion"></xsd:element>
                <xsd:element name="listadoBaja" type="tipobaja"></xsd:element>
                <xsd:element name="listadoprestaciones" type="tipoprestaciones"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="tipofecha">
        <xsd:sequence>
            <xsd:element name="dia" type="xsd:string"></xsd:element>
            <xsd:element name="mes" type="xsd:string"></xsd:element>
            <xsd:element name="aÃ±o" type="xsd:string"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tiposituacion">
        <xsd:sequence>
            <xsd:element name="en_paro" type="xsd:string"></xsd:element>
            <xsd:element name="laboral" type="xsd:string"></xsd:element>
            <xsd:element name="en_activo" type="xsd:string"></xsd:element>
            <xsd:element name="edad_no_laboral" type="xsd:string"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tipobaja">
        <xsd:sequence>
            <xsd:element name="causa" type="xsd:string"></xsd:element>
            <xsd:element name="fechaInicio" type="xsd:string"></xsd:element>
            <xsd:element name="fechaFinal" type="xsd:string"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tipoprestaciones">
        <xsd:sequence>
            <xsd:element name="cantidadPercibida" type="xsd:integer"></xsd:element>
            <xsd:element name="fechainicio" type="xsd:string"></xsd:element>
            <xsd:element name="fechafinal" type="xsd:string"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ICV-23-24/xml-schemas-JoanApr/EJERCICIOS_XML/Tarea2/Tarea2.xml
<?xml version="1.0" encoding="UTF-8"?>
<afiliado xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Tarea2.xsd">

    <DNI_NIE>45678934L</DNI_NIE>
    <nombre>Juan</nombre>
    <apellidos>Martinez Segovia</apellidos>
    <fechaNacimiento>
        <dia>28</dia>
        <mes>Julio</mes>
        <año>2002</año>
    </fechaNacimiento>
    <situacionLaboral>
        <en_paro>en paro</en_paro>
        <laboral>no</laboral>
        <en_activo>no_activo</en_activo>
        <edad_no_laboral>no</edad_no_laboral>
    </situacionLaboral>
    <listadoBaja>
        <causa>Caida de toro electrico</causa>
        <fechaInicio>12/01/2024</fechaInicio>
        <fechaFinal>20/01/2024</fechaFinal>
    </listadoBaja>
  
    <listadoprestaciones>
        <cantidadPercibida>2500</cantidadPercibida>
        <fechainicio>13/01/2024</fechainicio>
        <fechafinal>29/03/2024</fechafinal>
    </listadoprestaciones>

</afiliado>
